name: kwc
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - black=22.10.0
  - cookiecutter=2.1.1
  - cuda=11.7.1
  - fastai=2.7.10
  - fastapi=0.88.0
  - flake8=6.0.0
  - h11=0.12.0
  - isort=5.11.2
  - jupyter_contrib_nbextensions=0.7.0
  - matplotlib=3.6.2
  - mypy=0.991
  - notebook=6.5.2
  - pandas=1.5.2
  - pillow=9.2.0
  - pip=22.3.1
  - pipenv=2022.11.30
  - python=3.10.6
  - pytorch-cuda=11.7
  - scikit-learn=1.2.0
  - setuptools=65.5.1
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - uvicorn=0.20.0
  - pip:
      - protobuf==3.19.6
      - requests==2.25.1
