# WARNING: Not optimized for this project. I use this env for other projects
#          so contains packages not needed for this project. Will attempt to
#          clean it up when I get some time.
name: kwc
channels:
  - anaconda-platform
  - pytorch
  - fastai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.10.0
  - blas=1.0
  - bleach=5.0.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - catalogue=2.0.8
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - confection=0.0.3
  - contourpy=1.0.6
  - cookiecutter=2.1.1
  - cryptography=38.0.4
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.76
  - cuda-documentation=12.0.76
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.0.90
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cycler=0.11.0
  - cymem=2.0.7
  - cython-blis=0.7.9
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.4
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.6
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fastai=2.7.10
  - fastapi=0.88.0
  - fastcore=1.5.26
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.8.2
  - flake8=6.0.0
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - future=0.18.2
  - gds-tools=1.5.0.59
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.21.2
  - gstreamer=1.21.2
  - gstreamer-orc=0.4.33
  - h11=0.12.0
  - huggingface_hub=0.11.1
  - icu=70.1
  - importlib-metadata=5.1.0
  - importlib_metadata=5.1.0
  - importlib_resources=5.10.1
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - isort=5.11.2
  - jack=1.9.21
  - jedi=0.18.2
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.8
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.1.0
  - jupyter_events=0.5.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.0.1
  - jupyter_server_terminals=0.4.2
  - jupyterlab_pygments=0.2.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - kubectl=v1.5.1
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.6
  - libclang13=15.0.6
  - libcublas=12.0.1.189
  - libcublas-dev=12.0.1.189
  - libcufft=11.0.0.21
  - libcufft-dev=11.0.0.21
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcups=2.3.3
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.4.2.57
  - libcusolver-dev=11.4.2.57
  - libcusparse=12.0.0.76
  - libcusparse-dev=12.0.0.76
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgpg-error=1.45
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.6
  - libnpp=12.0.0.30
  - libnpp-dev=12.0.0.30
  - libnsl=2.0.0
  - libnvjpeg=12.0.0.28
  - libnvjpeg-dev=12.0.0.28
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - lxml=4.9.2
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=2.0.4
  - mkl=2022.2.1
  - mpg123=1.31.1
  - munkres=1.1.4
  - murmurhash=1.0.9
  - mypy=0.991
  - mypy_extensions=0.4.3
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.6
  - nbconvert-core=7.2.6
  - nbconvert-pandoc=7.2.6
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.6
  - ninja=1.11.0
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nsight-compute=2022.4.0.15
  - nspr=4.35
  - nss=3.82
  - numpy=1.23.5
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - pandas=1.5.2
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pathy=0.10.1
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pipenv=2022.11.30
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.0
  - ply=3.11
  - preshed=3.0.8
  - prettytable=3.5.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydantic=1.10.2
  - pyflakes=3.0.1
  - pygments=2.13.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-slugify=7.0.0
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.6
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - readline=8.1.2
  - scikit-learn=1.2.0
  - send2trash=1.8.0
  - setuptools=65.5.1
  - shellingham=1.5.0
  - sip=6.7.5
  - six=1.16.0
  - sleef=3.5.1
  - smart_open=5.2.1
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - spacy=3.4.3
  - spacy-legacy=3.0.10
  - spacy-loggers=1.0.3
  - srsly=2.4.5
  - stack_data=0.6.2
  - starlette=0.22.0
  - tbb=2021.7.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - thinc=8.1.5
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typer=0.4.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - unidecode=1.3.6
  - urllib3=1.26.13
  - uvicorn=0.20.0
  - virtualenv=20.17.1
  - virtualenv-clone=0.5.4
  - wasabi=0.10.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.3.0
      - accelerate==0.12.0
      - addict==2.4.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asgiref==3.5.2
      - async-timeout==4.0.2
      - backoff==2.2.1
      - basicsr==1.4.2
      - bcrypt==4.0.1
      - bentoml==1.0.12
      - boltons==21.0.0
      - boto3==1.26.29
      - botocore==1.29.29
      - build==0.9.0
      - cattrs==22.2.0
      - circus==0.18.0
      - clean-fid==0.1.29
      - click-option-group==0.5.5
      - clip==1.0
      - cloudpickle==2.2.0
      - commonmark==0.9.1
      - contextlib2==21.6.0
      - deepmerge==1.1.0
      - deprecated==1.2.13
      - einops==0.4.1
      - exceptiongroup==1.0.4
      - facexlib==0.2.5
      - fairscale==0.4.9
      - ffmpy==0.3.0
      - filetype==1.2.0
      - filterpy==1.4.5
      - font-roboto==0.0.1
      - fonts==0.0.3
      - frozenlist==1.3.3
      - fs==2.4.16
      - fs-s3fs==1.1.1
      - fsspec==2022.11.0
      - ftfy==6.1.1
      - gdown==4.6.0
      - gfpgan==1.3.8
      - gitpython==3.1.27
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - googleapis-common-protos==1.56.2
      - gradio==3.9
      - grpcio==1.51.1
      - grpcio-channelz==1.48.1
      - grpcio-health-checking==1.48.1
      - grpcio-reflection==1.48.1
      - httpcore==0.15.0
      - httpx==0.23.1
      - idna==2.10
      - imageio==2.22.4
      - inflection==0.5.1
      - jmespath==1.0.1
      - jsonmerge==1.8.0
      - kornia==0.6.7
      - lark==1.1.2
      - linkify-it-py==1.0.3
      - llvmlite==0.39.1
      - lmdb==1.4.0
      - lpips==0.1.4
      - markdown==3.4.1
      - markdown-it-py==2.1.0
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - multidict==6.0.3
      - networkx==2.8.8
      - numba==0.56.4
      - oauthlib==3.2.2
      - omegaconf==2.2.3
      - open-clip-torch==2.7.0
      - opencv-python==4.6.0.66
      - opentelemetry-api==1.14.0
      - opentelemetry-exporter-jaeger==1.14.0
      - opentelemetry-exporter-jaeger-proto-grpc==1.14.0
      - opentelemetry-exporter-jaeger-thrift==1.14.0
      - opentelemetry-exporter-otlp==1.14.0
      - opentelemetry-exporter-otlp-proto-grpc==1.14.0
      - opentelemetry-exporter-otlp-proto-http==1.14.0
      - opentelemetry-exporter-zipkin==1.14.0
      - opentelemetry-exporter-zipkin-json==1.14.0
      - opentelemetry-exporter-zipkin-proto-http==1.14.0
      - opentelemetry-instrumentation==0.35b0
      - opentelemetry-instrumentation-aiohttp-client==0.35b0
      - opentelemetry-instrumentation-asgi==0.35b0
      - opentelemetry-instrumentation-grpc==0.35b0
      - opentelemetry-proto==1.14.0
      - opentelemetry-sdk==1.14.0
      - opentelemetry-semantic-conventions==0.35b0
      - opentelemetry-util-http==0.35b0
      - orjson==3.8.3
      - packaging==21.3
      - paramiko==2.12.0
      - pep517==0.13.0
      - piexif==1.1.3
      - pip-requirements-parser==32.0.0
      - pip-tools==6.12.0
      - protobuf==3.19.6
      - pyarrow==10.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycryptodome==3.16.0
      - pydeprecate==0.3.2
      - pydub==0.25.1
      - pynacl==1.5.0
      - pynvml==11.4.1
      - python-json-logger==2.0.4
      - python-multipart==0.0.4
      - pytorch-lightning==1.7.6
      - pywavelets==1.4.1
      - realesrgan==0.3.0
      - regex==2022.10.31
      - requests==2.25.1
      - requests-oauthlib==1.3.1
      - resize-right==0.0.2
      - rfc3986==1.5.0
      - rich==12.6.0
      - rsa==4.9
      - s3transfer==0.6.0
      - safetensors==0.2.5
      - schema==0.7.5
      - scikit-image==0.19.2
      - scipy==1.9.3
      - sentencepiece==0.1.97
      - simple-di==0.1.5
      - tb-nightly==2.12.0a20221212
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - thrift==0.16.0
      - tifffile==2022.10.10
      - timm==0.6.7
      - tokenizers==0.12.1
      - torchdiffeq==0.2.3
      - torchmetrics==0.11.0
      - torchsde==0.2.5
      - trampoline==0.1.2
      - transformers==4.19.2
      - uc-micro-py==1.0.1
      - watchfiles==0.18.1
      - websockets==10.4
      - werkzeug==2.2.2
      - wrapt==1.14.1
      - yapf==0.32.0
      - yarl==1.8.2
